
# Copyright 2024 David Novak
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Generate figures used in `5_stats.Rmd` for demonstration purposes.

# Fig 1. Wilcoxon test ----

png(filename = '5_stats_fig1.png', width = 1600, height = 840, units = 'px')
par(family = 'Arial')
## Draw random grouped data ----
set.seed(1)
n0 <- 10
n1 <- 10
n <- n0+n1
x0 <- c(
  sample(x = seq(-5, 3, by = .1), size = ceiling(n0/5), replace = TRUE),
  sample(x = seq(1, 8, by = .1), size = floor(n0*.8)-1, replace = TRUE),
  13
)
x1 <- c(
  sample(x = seq(4, 11, by = .1), size = floor(n1*0.8), replace = TRUE),
  sample(x = seq(12, 14, by = .1), size = ceiling(n1*0.2), replace = TRUE)
)-2
x <- c(x0, x1)
cls <- as.factor(rep(c(0, 1), times = c(n0, n1)))
o <- order(x)
x <- x[o]
cls <- cls[o]

## Plot ----
colours <- c('darkblue', 'darkred')[cls]
par(mar = c(0,0,0,0))
plot(NULL, xlim = range(x), ylim = c(0.169, 0.455),
     axes = FALSE, xlab = '', ylab = '',
     main = '\n\nWilcoxon rank sum test', cex.main = 2.92)
box()

{
  x_ranks <- order(x)
  x_ranks <- x_ranks-min(x_ranks)
  x_ranks <- x_ranks/max(x_ranks)
  x_ranks <- x_ranks*diff(range(x))
  x_ranks <- x_ranks + min(x)
}

for (i in seq_along(x)) {
  lines(x = c(x_ranks[i], x[i]), y = c(0.25, 0.4), col = colours[i], lwd = 2)
}
points(x, rep(0.4, times = n), col = scales::alpha(colours, .5), pch = 20, cex = 8)
points(x_ranks, rep(0.245, times = n), col = colours, pch = '|', cex = 10)

lines(x = range(x0), y = rep(0.41, times = 2), lwd = 6, col = 'darkblue')
text(x = min(x0)+diff(range(x0))/2, y = 0.415, labels = expression(bold('data from group A')), col = 'darkblue', cex = 2)

lines(x = range(x1), y = rep(0.422, times = 2), lwd = 6, col = 'darkred')
text(x = min(x1)+diff(range(x1))/2, y = 0.427, labels = expression(bold('data from group B')), col = 'darkred', cex = 2)



lines(x = range(x_ranks[cls==0]), y = rep(0.221, times = 2), lwd = 6, col = 'darkblue')
text(x = min(x_ranks[cls==0])+diff(range(x_ranks[cls==0]))/2, y = 0.214, labels = expression(bold('ranks of data from group A')), col = 'darkblue')

lines(x = range(x_ranks[cls==1]), y = rep(0.207, times = 2), lwd = 6, col = 'darkred')
text(x = min(x_ranks[cls==1])+diff(range(x_ranks[cls==1]))/2, y = 0.200, labels = expression(bold('ranks of data from group B')), col = 'darkred')


text(x = min(x)+diff(range(x))/2, y = 0.18, label = expression(bold('How likely is it that the samples come from different distributions, based on the ranks?')), cex = 2.4)

dev.off()

# Fig 2. Fixed and random effects ----
##mostly generated by Gemini

png(filename = '5_stats_fig3.png', width = 1600, height = 840, units = 'px')
par(family = 'Arial')
{
# Set seed for reproducibility
set.seed(123)

# Define number of data points per group
n.points <- 60

# Generate random slopes for each group
group.slopes <- rnorm(3, mean = 1, sd = 0.2)

# Generate random intercepts for each group
group.intercepts <- rnorm(3, mean = 5, sd = 2)

# Combine data into a dataframe
data <- data.frame(group = factor(rep(1:3, each = n.points)))

# Generate x-values
data$x <- runif(nrow(data), min = 1, max = 10)

# Generate y-values with group effects
data$y <- group.slopes[data$group] * data$x + 
  group.intercepts[data$group] + 
  rnorm(nrow(data), mean = 0, sd = 1)  # Add random error

# Linear mixed model with lme4 package (replace lm with lmer)
library(lme4)  # Load lme4 package for mixed models
lmer.model <- lmer(y ~ x + (1 | group), data = data)

# Extract fitted values using predict with intervals=FALSE
fitted.values <- data.frame(
  x = data$x,
  group = data$group,
  fit = predict(lmer.model, newdata = data)
)
# fitted.values <- subset(fitted.values, fitted.values$x %in% data$x)
# Generate plot
par(mar=c(5,5,5,5))
colours <- c('darkblue','darkgreen','brown')[fitted.values$group]
plot(data$x, data$y, pch = 16, xlim = c(0, 11), ylim = c(0, 20), 
     xlab = "predictor (X)", ylab = "response (Y)", col = scales::alpha(colours, .4),cex.main=3.0,
     main = "Linear Mixed Model with Random Intercepts (by Batch)", cex = 2,cex.sub=2,cex.main=2,cex.lab=2,cex.axis=2)
lines(fitted.values[fitted.values$group == 1,]$x, 
      fitted.values[fitted.values$group == 1,]$fit, col = "darkblue", lwd = 8)
lines(fitted.values[fitted.values$group == 2,]$x, 
      fitted.values[fitted.values$group == 2,]$fit, col = "darkgreen", lwd = 8)
lines(fitted.values[fitted.values$group == 3,]$x, 
      fitted.values[fitted.values$group == 3,]$fit, col = "brown", lwd = 8)

# Add legend
legend("topright", legend = c("Batch 1", "Batch 2", "Batch 3"), 
       col = c("darkblue", "darkgreen", "brown"), lty = 2, lwd = 10, cex = 2.5)

}
dev.off()
